default_stages:
  - pre-commit

repos:
  # - repo: local
  #   hooks:
  #     - id: git-config
  #       name: Modify git config
  #       description: Modify git config to use ; as comment character
  #       language: system
  #       pass_filenames: false
  #       entry:
  #         git config --local core.commentChar ';'
  #       always_run: true

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: debug-statements

  # - repo: https://github.com/pycqa/isort
  #   rev: 6.1.0
  #   hooks:
  #     - id: isort
  #       args: ["--profile", "black"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.2
    hooks:
      - id: ruff-check
        args: [
          --fix,
          --config=.ruff.toml
        ]
      - id: ruff-format
        args: [
          --config=.ruff.toml
        ]
        types_or: [ python, pyi ]

  - repo: local
    hooks:
      - id: pytest-check-fast
        name: pytest (fast)
        entry: uv run pytest
        language: system
        pass_filenames: false
        types_or: [ python, pyi ]
        args: [
          --config-file=.pytest.ini,
          -m not integration and not slow,
          --tb=short,
          --no-cov
        ]

      - id: pytest-check-all
        name: pytest (all)
        entry: uv run pytest
        language: system
        pass_filenames: false
        types_or: [ python, pyi ]
        args: [
            --config-file=.pytest.ini,
            --cov-config=.coveragerc,
            --cov-report=term-missing,
            --cov-fail-under=90,
            --tb=short
        ]
        stages: [pre-push]
